# Generated by Django 4.2.8 on 2023-12-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_rename_productbarcode_barcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/product_raw_image/")),
                ("task_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
