# Generated by Django 4.2.7 on 2023-12-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0001_initial"),
        ("product", "0004_tagimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=128, unique=True)),
                ("sold", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="barcode",
            name="product",
        ),
        migrations.DeleteModel(
            name="TagImage",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="processed",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tag_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/tag_images/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="article_number",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.brand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.color",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/product_images/"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="mrp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="wsp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=32, null=True
            ),
        ),
        migrations.RenameModel(
            old_name="ProductQuantity",
            new_name="PTFileData",
        ),
        migrations.DeleteModel(
            name="Barcode",
        ),
        migrations.AddField(
            model_name="productbarcode",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.ptfiledata"
            ),
        ),
    ]
