# Generated by Django 4.2.7 on 2023-12-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tag_image",
            field=models.ImageField(blank=True, null=True, upload_to="tag_images/"),
        ),
    ]
