# Generated by Django 4.2.7 on 2023-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_product_brand_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="mrp",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="wsp",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
