# Generated by Django 4.2.7 on 2023-12-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_product_mrp_alter_product_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
