# Generated by Django 4.2.7 on 2024-01-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_rename_image_product_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTagImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_images/"
                    ),
                ),
                (
                    "tag_image",
                    models.ImageField(blank=True, null=True, upload_to="tag_images/"),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="product",
            old_name="color",
            new_name="hash_value",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="meta_data",
            new_name="metadata",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mrp",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="tag_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="wsp",
        ),
        migrations.AddField(
            model_name="ptfiledata",
            name="color",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="ptfiledata",
            name="mrp",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="ptfiledata",
            name="size",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="ptfiledata",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                ],
                default="PROCESSING",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="ptfiledata",
            name="wsp",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="product_images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.producttagimage",
            ),
        ),
    ]
