# Generated by Django 4.2.8 on 2024-01-08 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_productimages_rename_meta_data_product_metadata_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductImages",
            new_name="ProductTagImage",
        ),
    ]
