# Generated by Django 4.2.8 on 2024-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_productimages_rename_meta_data_product_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hash_value",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
