# Generated by Django 4.2.9 on 2024-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_rename_ptfiledata_ptfileentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptfileentry",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
