# Generated by Django 4.2.9 on 2024-01-13 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_genre_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
