# Generated by Django 4.2.8 on 2024-01-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_remove_movie_genre_delete_genre_delete_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbarcode",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
        ),
    ]
