# Generated by Django 4.2.8 on 2024-03-23 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_category_department_subcategory_category_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Subcategory",
        ),
    ]
