# Generated by Django 4.2.8 on 2024-02-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_remove_subcategory_category_delete_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productbarcode",
            name="batch_id",
            field=models.CharField(default=None, max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
