# Generated by Django 4.2.8 on 2024-02-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0021_productbarcode_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbarcode",
            name="batch_id",
            field=models.CharField(max_length=1024),
        ),
    ]
