# Generated by Django 4.2.7 on 2024-03-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0001_initial"),
        ("product", "0022_alter_productbarcode_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
        ),
    ]
