# Generated by Django 4.2.9 on 2024-03-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0001_initial"),
        ("product", "0023_alter_product_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                max_length=64,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                max_length=64,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.subcategory",
            ),
        ),
    ]
