# Generated by Django 4.2.9 on 2024-03-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0002_brand"),
        ("product", "0024_alter_product_category_alter_product_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                max_length=64,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.brand",
            ),
        ),
    ]
