# Generated by Django 4.2.8 on 2024-04-03 17:15

import apps.product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0025_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfileentry",
            name="is_exported",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PTFileBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        default=apps.product.models.PTFileBatch.generate_batch_id,
                        max_length=20,
                    ),
                ),
                ("is_file_uploaded", models.BooleanField(default=False)),
                (
                    "pt_file_entries",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.ptfileentry",
                    ),
                ),
            ],
        ),
    ]
