# Generated by Django 4.2.8 on 2024-04-03 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0026_ptfileentry_is_exported_ptfilebatch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ptfilebatch",
            name="pt_file_entries",
        ),
        migrations.AddField(
            model_name="ptfilebatch",
            name="ptfile_entry_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
    ]
