# Generated by Django 4.2.8 on 2024-04-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0027_remove_ptfilebatch_pt_file_entries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfileentry",
            name="barcode",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
