# Generated by Django 4.2.8 on 2024-04-05 03:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0028_ptfileentry_barcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ptfileentry",
            name="barcode",
        ),
    ]
