# Generated by Django 4.2.7 on 2024-04-06 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0029_remove_ptfileentry_barcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="processed",
        ),
    ]
