# Generated by Django 4.2.7 on 2024-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0030_remove_product_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ptfileentry",
            name="is_exported",
        ),
        migrations.AddField(
            model_name="ptfilebatch",
            name="is_exported",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ptfileentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("ENTRY", "Entry"),
                    ("LIST", "List"),
                    ("BARCODE", "Barcode"),
                    ("COMPLETED", "Completed"),
                ],
                default="ENTRY",
                max_length=64,
            ),
        ),
    ]
