# Generated by Django 4.2.7 on 2024-04-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0031_remove_ptfileentry_is_exported_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbarcode",
            name="batch_id",
        ),
        migrations.RemoveField(
            model_name="productbarcode",
            name="product",
        ),
        migrations.AddField(
            model_name="productbarcode",
            name="pt_entry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.ptfileentry",
            ),
        ),
    ]
