# Generated by Django 4.2.7 on 2024-04-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0032_remove_productbarcode_batch_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptfileentry",
            name="mrp",
            field=models.CharField(blank=True, default=0, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="ptfileentry",
            name="size",
            field=models.CharField(blank=True, default=0, max_length=128, null=True),
        ),
    ]
