# Generated by Django 4.2.7 on 2024-04-06 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0033_alter_ptfileentry_mrp_alter_ptfileentry_size"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductTagImage",
            new_name="ProductImage",
        ),
    ]
