# Generated by Django 4.2.11 on 2024-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0034_rename_producttagimage_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ptfileentry",
            old_name="wsp",
            new_name="invoice_number",
        ),
        migrations.AddField(
            model_name="ptfileentry",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptfileentry",
            name="per_price",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="ptfileentry",
            name="suffix",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
