# Generated by Django 4.2.9 on 2024-04-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0005_size"),
        ("product", "0035_rename_wsp_ptfileentry_invoice_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptfileentry",
            name="size",
            field=models.ForeignKey(
                blank=True,
                max_length=64,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.size",
            ),
        ),
    ]
