# Generated by Django 4.2.9 on 2024-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0036_alter_ptfileentry_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfilebatch",
            name="is_image_exported",
            field=models.BooleanField(default=False),
        ),
    ]
