# Generated by Django 4.2.9 on 2024-05-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0015_color"),
        ("product", "0037_ptfilebatch_is_image_exported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptfileentry",
            name="color",
            field=models.ForeignKey(
                blank=True,
                max_length=64,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.color",
            ),
        ),
    ]
