# Generated by Django 4.2.9 on 2024-05-11 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0038_alter_ptfileentry_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ptfileentry",
            old_name="per_price",
            new_name="pur_price",
        ),
    ]
