# Generated by Django 4.2.9 on 2024-05-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0039_rename_per_price_ptfileentry_pur_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfileentry",
            name="color_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
