# Generated by Django 4.2.9 on 2024-05-26 17:08

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0040_ptfileentry_color_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ptfilebatch",
            name="batch_id",
            field=models.CharField(
                default=apps.product.models.PTFileBatch.generate_batch_id,
                max_length=1024,
            ),
        ),
    ]
