# Generated by Django 4.2.7 on 2024-06-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0041_alter_ptfilebatch_batch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfilebatch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
