# Generated by Django 4.2.9 on 2024-06-13 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0042_ptfilebatch_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ptfileentry",
            name="color_code",
        ),
    ]
