# Generated by Django 4.2.7 on 2024-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0043_remove_ptfileentry_color_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
