# Generated by Django 4.2.9 on 2024-06-26 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0044_productimage_metadata"),
        ("product", "0044_ptfileentry_color_code"),
    ]

    operations = []
