# Generated by Django 4.2.11 on 2024-07-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0045_merge_20240626_2340"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="po_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
