# Generated by Django 4.2.11 on 2024-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0046_product_po_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfilebatch",
            name="is_exported_for_po",
            field=models.BooleanField(default=False),
        ),
    ]
