# Generated by Django 4.2.7 on 2024-07-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0016_alter_category_prefix"),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procurmentitem",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="procurmentitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="procurmentitem",
            name="color",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="procurmentitem",
            name="quantity_and_size",
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name="procurmentorder",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.brand",
            ),
        ),
        migrations.AddField(
            model_name="procurmentorder",
            name="intent_number",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="procurmentorder",
            name="terms_of_shipment",
            field=models.CharField(
                default="Please Send All Good As soon As Possible.",
                max_length=1024,
                null=True,
            ),
        ),
    ]
