# Generated by Django 4.2.7 on 2024-07-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0045_merge_20240626_2340"),
        ("department", "0016_alter_category_prefix"),
        ("procurement", "0002_remove_procurmentitem_brand_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(default=None, max_length=512, null=True)),
                ("quantity_and_size", models.JSONField(default=None)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="ProcurmentOrder",
            new_name="ProcurementOrder",
        ),
        migrations.DeleteModel(
            name="ProcurmentItem",
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procurement_order",
                to="procurement.procurementorder",
            ),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
        ),
    ]
