# Generated by Django 4.2.11 on 2024-07-11 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0003_procurementitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementorder",
            name="due_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
