# Generated by Django 4.2.9 on 2024-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0004_procurementorder_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurementorder",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
