# Generated by Django 4.2.11 on 2024-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0006_alter_procurementorder_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementorder",
            name="admin_approve_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                max_length=16,
            ),
        ),
    ]
