# Generated by Django 4.2.11 on 2024-07-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0007_procurementorder_admin_approve_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementitem",
            name="color_code",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="notes",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="procurementitem",
            name="remarks",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="procurementorder",
            name="tnc",
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="procurementorder",
            name="admin_approve_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
