# Generated by Django 4.2.11 on 2024-07-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "procurement",
            "0008_procurementitem_color_code_procurementitem_notes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsandCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tnc", models.CharField(default=None, max_length=2048, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="procurementorder",
            name="tnc",
        ),
    ]
