# Generated by Django 4.2.9 on 2024-07-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0009_termsandcondition_remove_procurementorder_tnc"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementorder",
            name="po",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
