# Generated by Django 4.2.9 on 2024-07-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0010_procurementorder_po"),
    ]

    operations = [
        migrations.AddField(
            model_name="procurementorder",
            name="type",
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
