# Generated by Django 4.2.8 on 2023-12-18 14:47

import apps.user.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.user.managers.CustomUserManager()),
            ],
        ),
    ]
