# Generated by Django 4.2.9 on 2024-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("CO", "Company Owner"),
                    ("FT", "Feeding Team"),
                    ("BT", "Barcode Team"),
                ],
                default="BT",
                max_length=2,
            ),
        ),
    ]
