# Generated by Django 4.2.9 on 2024-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0002_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="brand_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
