# Generated by Django 4.2.11 on 2024-04-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0003_brand_brand_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="supplier_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
