# Generated by Django 4.2.9 on 2024-04-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0005_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="size_value",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
