# Generated by Django 4.2.9 on 2024-04-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0006_alter_size_size_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
        ),
    ]
