# Generated by Django 4.2.7 on 2024-04-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0007_alter_size_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="prefix",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="suffix",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="department",
            name="suffix",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="suffix",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
