# Generated by Django 4.2.7 on 2024-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0008_brand_prefix_category_suffix_department_suffix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="prefix",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="department",
            name="suffix",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="suffix",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
