# Generated by Django 4.2.9 on 2024-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0009_alter_brand_prefix_alter_category_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
