# Generated by Django 4.2.7 on 2024-05-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0011_alter_category_department_alter_subcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="department.department",
            ),
        ),
    ]
