# Generated by Django 4.2.7 on 2024-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0012_alter_size_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="hsn_code",
        ),
        migrations.AddField(
            model_name="category",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
