# Generated by Django 4.2.7 on 2024-05-09 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0013_remove_department_hsn_code_category_hsn_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="prefix",
            new_name="suffix",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="suffix",
            new_name="prefix",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="suffix",
            new_name="prefix",
        ),
        migrations.RenameField(
            model_name="subcategory",
            old_name="suffix",
            new_name="prefix",
        ),
    ]
