# Generated by Django 4.2.9 on 2024-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0014_rename_prefix_brand_suffix_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=64)),
            ],
        ),
    ]
