# Generated by Django 4.2.9 on 2024-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0015_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="prefix",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
