# Generated by Django 4.2.11 on 2024-07-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("department", "0016_alter_category_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="address",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
